import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const currentDir = path.dirname(fileURLToPath(import.meta.url));
const repositoryRoot = path.resolve(currentDir, "..");
const versionScript = path.join(repositoryRoot, "scripts", "version.mjs");

const VERSION_SCRIPTS = {
  "version:get": "node scripts/version.mjs get",
  "version:check": "node scripts/version.mjs check",
  "version:set": "node scripts/version.mjs set",
  "version:bump": "node scripts/version.mjs bump",
};

function writeFixtureFile(root, relativePath, content) {
  const filePath = path.join(root, relativePath);
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, "utf8");
  return filePath;
}

function createFixture({
  version = "0.2.0",
  withInstallerActions = true,
  eol = "\n",
} = {}) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "fyagent-version-test-"));
  fs.mkdirSync(path.join(root, "scripts"), { recursive: true });
  fs.copyFileSync(versionScript, path.join(root, "scripts", "version.mjs"));

  writeFixtureFile(
    root,
    "package.json",
    JSON.stringify(
      {
        name: "fyagent",
        private: true,
        scripts: VERSION_SCRIPTS,
      },
      null,
      2,
    ) + eol,
  );
  writeFixtureFile(
    root,
    "src-tauri/tauri.conf.json",
    JSON.stringify(
      {
        productName: "FyAgent",
        identifier: "com.fyagent.desktop",
      },
      null,
      2,
    ) + eol,
  );

  const members = withInstallerActions
    ? 'members = [".", "installer-actions"]'
    : 'members = ["."]';
  writeFixtureFile(
    root,
    "src-tauri/Cargo.toml",
    [
      "[workspace]",
      members,
      'resolver = "2"',
      "",
      "[workspace.package]",
      'version = "' + version + '"',
      "",
      "[package]",
      'name = "fyagent"',
      "version.workspace = true",
      'edition = "2021"',
      "",
    ].join(eol),
  );

  if (withInstallerActions) {
    writeFixtureFile(
      root,
      "src-tauri/installer-actions/Cargo.toml",
      [
        "[package]",
        'name = "fyagent-installer-actions"',
        "version.workspace = true",
        'edition = "2021"',
        "publish = false",
        "",
      ].join(eol),
    );
  }

  const helperBlock = withInstallerActions
    ? [
        "",
        "[[package]]",
        'name = "fyagent-installer-actions"',
        'version = "' + version + '"',
      ]
    : [];
  writeFixtureFile(
    root,
    "src-tauri/Cargo.lock",
    [
      "# This file is automatically @generated by Cargo.",
      "version = 4",
      "",
      "[[package]]",
      'name = "dependency-a"',
      'version = "0.2.0"',
      "",
      "[[package]]",
      'name = "fyagent"',
      'version = "' + version + '"',
      ...helperBlock,
      "",
      "[[package]]",
      'name = "dependency-b"',
      'version = "0.2.0"',
      "",
    ].join(eol),
  );

  return root;
}

function removeFixture(root) {
  fs.rmSync(root, { recursive: true, force: true });
}

function run(root, ...args) {
  return spawnSync(process.execPath, ["scripts/version.mjs", ...args], {
    cwd: root,
    encoding: "utf8",
  });
}

function runWithEnvironment(root, environment, ...args) {
  return spawnSync(process.execPath, ["scripts/version.mjs", ...args], {
    cwd: root,
    encoding: "utf8",
    env: { ...process.env, ...environment },
  });
}

function readFixture(root, relativePath) {
  return fs.readFileSync(path.join(root, relativePath), "utf8");
}

function writeFixture(root, relativePath, content) {
  fs.writeFileSync(path.join(root, relativePath), content, "utf8");
}

function readJsonFixture(root, relativePath) {
  return JSON.parse(readFixture(root, relativePath));
}

function writeJsonFixture(root, relativePath, value) {
  writeFixture(root, relativePath, JSON.stringify(value, null, 2) + "\n");
}

test("set updates only the canonical Cargo value and local lock entries", (t) => {
  const root = createFixture();
  t.after(() => removeFixture(root));

  const packageBefore = readFixture(root, "package.json");
  const tauriBefore = readFixture(root, "src-tauri/tauri.conf.json");
  const result = run(root, "set", "0.2.1");

  assert.equal(result.status, 0, result.stderr);
  assert.match(
    readFixture(root, "src-tauri/Cargo.toml"),
    /\[workspace\.package\][\s\S]*version = "0\.2\.1"/,
  );

  const lock = readFixture(root, "src-tauri/Cargo.lock");
  assert.match(lock, /name = "fyagent"\nversion = "0\.2\.1"/);
  assert.match(lock, /name = "fyagent-installer-actions"\nversion = "0\.2\.1"/);
  assert.equal(
    (lock.match(/name = "dependency-[ab]"\nversion = "0\.2\.0"/g) ?? []).length,
    2,
  );
  assert.equal(readFixture(root, "package.json"), packageBefore);
  assert.equal(readFixture(root, "src-tauri/tauri.conf.json"), tauriBefore);
});

test("check enforces exact release tag equality", (t) => {
  const root = createFixture();
  t.after(() => removeFixture(root));

  assert.equal(run(root, "check", "--", "--tag", "v0.2.0").status, 0);
  const mismatch = run(root, "check", "--", "--tag", "v0.2.1");
  assert.equal(mismatch.status, 1);
  assert.match(mismatch.stderr, /release tag must be v0\.2\.0/);
});

test("get prints only the canonical application version", (t) => {
  const root = createFixture();
  t.after(() => removeFixture(root));

  const result = run(root, "get");
  assert.equal(result.status, 0, result.stderr);
  assert.equal(result.stdout, "0.2.0\n");
  assert.equal(result.stderr, "");
});

test("set rejects prerelease, v-prefixed, and MSI-incompatible values", (t) => {
  const root = createFixture({ withInstallerActions: false });
  t.after(() => removeFixture(root));

  for (const invalid of [
    "v0.2.1",
    "0.2.1-beta.1",
    "0.2.1+build.2",
    "256.0.0",
    "0.256.0",
    "0.0.65536",
  ]) {
    const result = run(root, "set", invalid);
    assert.equal(result.status, 1, invalid + ": " + result.stderr);
  }
  assert.match(run(root, "set", "v0.2.1").stderr, /stable SemVer X\.Y\.Z/);
  assert.match(run(root, "set", "256.0.0").stderr, /ProductVersion limits/);
});

test("dry-run reports both writable targets without modifying either", (t) => {
  const root = createFixture();
  t.after(() => removeFixture(root));
  const cargoBefore = readFixture(root, "src-tauri/Cargo.toml");
  const lockBefore = readFixture(root, "src-tauri/Cargo.lock");

  const result = run(root, "set", "0.2.1", "--dry-run");
  assert.equal(result.status, 0, result.stderr);
  assert.match(result.stdout, /would update src-tauri\/Cargo\.toml/);
  assert.match(result.stdout, /would update src-tauri\/Cargo\.lock/);
  assert.equal(readFixture(root, "src-tauri/Cargo.toml"), cargoBefore);
  assert.equal(readFixture(root, "src-tauri/Cargo.lock"), lockBefore);
});

test("bump implements stable SemVer arithmetic", (t) => {
  const cases = [
    ["patch", "0.2.1"],
    ["minor", "0.3.0"],
    ["major", "1.0.0"],
  ];

  for (const [kind, expected] of cases) {
    const root = createFixture();
    t.after(() => removeFixture(root));
    const result = run(root, "bump", kind);
    assert.equal(result.status, 0, kind + ": " + result.stderr);
    const getResult = run(root, "get");
    assert.equal(getResult.status, 0, getResult.stderr);
    assert.equal(getResult.stdout.trim(), expected);
  }
});

test("bump rejects a result above the MSI ProductVersion range", (t) => {
  const root = createFixture({ version: "255.255.65535" });
  t.after(() => removeFixture(root));
  const cargoBefore = readFixture(root, "src-tauri/Cargo.toml");
  const lockBefore = readFixture(root, "src-tauri/Cargo.lock");

  const result = run(root, "bump", "major");
  assert.equal(result.status, 1);
  assert.match(result.stderr, /ProductVersion limits/);
  assert.equal(readFixture(root, "src-tauri/Cargo.toml"), cargoBefore);
  assert.equal(readFixture(root, "src-tauri/Cargo.lock"), lockBefore);
});

test("check rejects duplicate metadata fields and a missing command", (t) => {
  const root = createFixture();
  t.after(() => removeFixture(root));

  const packageJson = readJsonFixture(root, "package.json");
  packageJson.version = "0.2.0";
  delete packageJson.scripts["version:check"];
  writeJsonFixture(root, "package.json", packageJson);

  const tauriPath = "src-tauri/tauri.conf.json";
  const tauriConfig = readJsonFixture(root, tauriPath);
  tauriConfig.version = "0.2.0";
  writeJsonFixture(root, tauriPath, tauriConfig);

  const result = run(root, "check");
  assert.equal(result.status, 1);
  assert.match(result.stderr, /package\.json must not declare/);
  assert.match(result.stderr, /scripts\.version:check/);
  assert.match(result.stderr, /tauri\.conf\.json must omit version/);
});

test("check requires workspace shape, package inheritance, and local package names", (t) => {
  const root = createFixture();
  t.after(() => removeFixture(root));
  const cargoPath = "src-tauri/Cargo.toml";
  const helperPath = "src-tauri/installer-actions/Cargo.toml";

  writeFixture(
    root,
    cargoPath,
    readFixture(root, cargoPath)
      .replace('members = [".", "installer-actions"]', 'members = ["."]')
      .replace('resolver = "2"', 'resolver = "1"')
      .replace("version.workspace = true", 'version = "0.2.0"'),
  );
  writeFixture(
    root,
    helperPath,
    readFixture(root, helperPath).replace(
      'name = "fyagent-installer-actions"',
      'name = "wrong-helper"',
    ),
  );

  const result = run(root, "check");
  assert.equal(result.status, 1);
  assert.match(result.stderr, /members must be/);
  assert.match(result.stderr, /resolver must be "2"/);
  assert.match(result.stderr, /must use exactly one version\.workspace/);
  assert.match(result.stderr, /name must be "fyagent-installer-actions"/);
});

test("check rejects missing or non-local workspace lock package entries", (t) => {
  const root = createFixture();
  t.after(() => removeFixture(root));
  const lockPath = "src-tauri/Cargo.lock";
  const original = readFixture(root, lockPath);

  writeFixture(
    root,
    lockPath,
    original.replace(
      'name = "fyagent"\nversion = "0.2.0"',
      'name = "fyagent"\nversion = "0.2.0"\nsource = "registry+https://example.invalid"',
    ),
  );
  let result = run(root, "check");
  assert.equal(result.status, 1);
  assert.match(
    result.stderr,
    /must be a local workspace package without source/,
  );

  writeFixture(
    root,
    lockPath,
    original.replace(
      '\n[[package]]\nname = "fyagent-installer-actions"\nversion = "0.2.0"\n',
      "\n",
    ),
  );
  result = run(root, "check");
  assert.equal(result.status, 1);
  assert.match(
    result.stderr,
    /missing local package fyagent-installer-actions/,
  );
});

test("set repairs version drift in local lock entries without touching dependencies", (t) => {
  const root = createFixture();
  t.after(() => removeFixture(root));
  const lockPath = "src-tauri/Cargo.lock";
  const drifted = readFixture(root, lockPath).replace(
    'name = "fyagent"\nversion = "0.2.0"',
    'name = "fyagent"\nversion = "0.1.9"',
  );
  writeFixture(root, lockPath, drifted);

  const result = run(root, "set", "0.2.1");
  assert.equal(result.status, 0, result.stderr);
  const lock = readFixture(root, lockPath);
  assert.match(lock, /name = "fyagent"\nversion = "0\.2\.1"/);
  assert.match(lock, /name = "fyagent-installer-actions"\nversion = "0\.2\.1"/);
  assert.match(lock, /name = "dependency-a"\nversion = "0\.2\.0"/);
  assert.match(lock, /name = "dependency-b"\nversion = "0\.2\.0"/);
});

test("set refuses an invalid structural contract before writing", (t) => {
  const root = createFixture();
  t.after(() => removeFixture(root));
  const packagePath = "package.json";
  const packageJson = readJsonFixture(root, packagePath);
  packageJson.version = "0.2.0";
  writeJsonFixture(root, packagePath, packageJson);

  const cargoBefore = readFixture(root, "src-tauri/Cargo.toml");
  const lockBefore = readFixture(root, "src-tauri/Cargo.lock");
  const result = run(root, "set", "0.2.1");
  assert.equal(result.status, 1);
  assert.match(result.stderr, /cannot update an invalid version contract/);
  assert.equal(readFixture(root, "src-tauri/Cargo.toml"), cargoBefore);
  assert.equal(readFixture(root, "src-tauri/Cargo.lock"), lockBefore);
});

test("set restores the canonical value when a later lock write fails", (t) => {
  const root = createFixture();
  t.after(() => removeFixture(root));
  const hookPath = path.join(root, "fail-lock-write.cjs");
  writeFixture(
    root,
    "fail-lock-write.cjs",
    [
      'const fs = require("node:fs");',
      'const path = require("node:path");',
      "const originalWriteFileSync = fs.writeFileSync;",
      "fs.writeFileSync = function patchedWriteFileSync(filePath, data, ...args) {",
      '  if (process.env.FYAGENT_VERSION_TEST_FAIL_LOCK_WRITE === "1" &&',
      '      path.basename(String(filePath)) === "Cargo.lock" &&',
      "      String(data).includes('version = \"0.2.1\"')) {",
      '    const error = new Error("injected Cargo.lock write failure");',
      '    error.code = "EIO";',
      "    throw error;",
      "  }",
      "  return originalWriteFileSync.call(this, filePath, data, ...args);",
      "};",
      "",
    ].join("\n"),
  );

  const cargoBefore = readFixture(root, "src-tauri/Cargo.toml");
  const lockBefore = readFixture(root, "src-tauri/Cargo.lock");
  const nodeOptions = [process.env.NODE_OPTIONS ?? "", "--require=" + hookPath]
    .filter(Boolean)
    .join(" ");
  const result = runWithEnvironment(
    root,
    {
      FYAGENT_VERSION_TEST_FAIL_LOCK_WRITE: "1",
      NODE_OPTIONS: nodeOptions,
    },
    "set",
    "0.2.1",
  );

  assert.equal(result.status, 1);
  assert.match(result.stderr, /rollback succeeded/);
  assert.equal(readFixture(root, "src-tauri/Cargo.toml"), cargoBefore);
  assert.equal(readFixture(root, "src-tauri/Cargo.lock"), lockBefore);
});

test("the contract parser accepts CRLF Cargo manifests and lockfiles", (t) => {
  const root = createFixture({ eol: "\r\n" });
  t.after(() => removeFixture(root));

  const checkResult = run(root, "check");
  assert.equal(checkResult.status, 0, checkResult.stderr);
  const setResult = run(root, "set", "0.2.1");
  assert.equal(setResult.status, 0, setResult.stderr);
  assert.equal(run(root, "check").status, 0);
});
